# -*- coding: utf-8 -*-
"""LSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cfRvK7-0Cs04KvLuCcV2OOdd2EQVFXTR
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
import warnings
from datetime import datetime, timedelta
import pickle
import json

# ========================================
# LSTM Stock Price Prediction - 3 Day Forecast
# ========================================
# Set plotting style
plt.style.use('seaborn-v0_8-darkgrid')

# ========================================
# Configuration
# ========================================
STOCK_SYMBOL = "AXISBANK.NS"  # Change to any stock symbol
TRAIN_START = "2020-01-01"   # 5 years of training data
TRAIN_END = "2025-11-05"      # Train up to October 2024
TIME_STEPS = 60               # Use 60 days to predict
FORECAST_DAYS = 3             # Predict next 3 days

print(f"\n⚙️ Configuration:")
print(f"   Stock Symbol: {STOCK_SYMBOL}")
print(f"   Training Period: {TRAIN_START} to {TRAIN_END}")
print(f"   Time Steps: {TIME_STEPS} days")
print(f"   Forecast Horizon: {FORECAST_DAYS} days")

# ========================================
# Step 1: Fetch Training Data
# ========================================
print(f"\n📊 Fetching training data for {STOCK_SYMBOL}...")
data = yf.download(STOCK_SYMBOL, start=TRAIN_START, end=TRAIN_END)


# Check if data is downloaded
if data.empty:
    print(f"❌ No data returned for {STOCK_SYMBOL}")
    raise ValueError("No data available. Check symbol or date range.")

# Reset index to make Date a column
data = data.reset_index()

# Fix column names
if isinstance(data.columns, pd.MultiIndex):
    data.columns = ['_'.join(map(str, col)).strip('_').lower()
                    if isinstance(col, tuple) else str(col).lower()
                    for col in data.columns]
else:
    data.columns = [str(col).lower().strip() for col in data.columns]

# Remove ticker suffix from column names
new_columns = {}
for col in data.columns:
    clean_col = col.split('_')[0] if '_' in col and col != 'date' else col
    new_columns[col] = clean_col
data.rename(columns=new_columns, inplace=True)

print(f"✅ Data fetched successfully!")
print(f"   Total records: {len(data)}")
print(f"   Date range: {data['date'].min()} to {data['date'].max()}")
print(f"   Columns: {list(data.columns)}")

# ========================================
# Step 2: Data Visualization
# ========================================
print("\n📊 Generating visualizations...")

x_axis = data['date'] if 'date' in data.columns else data.index

# Plot Close Price
fig, ax = plt.subplots(figsize=(14, 6))
ax.plot(x_axis, data['close'], label="Close Price", color="blue", linewidth=1.5)
ax.set_title(f"{STOCK_SYMBOL} - Historical Close Price", fontsize=16, fontweight='bold')
ax.set_xlabel("Date", fontsize=12)
ax.set_ylabel("Price (₹)", fontsize=12)
ax.legend()
ax.grid(True, alpha=0.3)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# ========================================
# Step 3: Prepare Training Data
# ========================================
print("\n🔧 Preparing training data...")
stock_close = data[['close']].copy()
dataset = stock_close.values
training_data_len = int(np.ceil(len(dataset) * 0.95))

print(f"   Total samples: {len(dataset)}")
print(f"   Training samples: {training_data_len}")
print(f"   Testing samples: {len(dataset) - training_data_len}")

# Scale the data
scaler = StandardScaler()
scaled_data = scaler.fit_transform(dataset)

# Create training sequences
training_data = scaled_data[:training_data_len]
X_train, y_train = [], []

for i in range(TIME_STEPS, len(training_data)):
    X_train.append(training_data[i-TIME_STEPS:i, 0])
    y_train.append(training_data[i, 0])

X_train, y_train = np.array(X_train), np.array(y_train)
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))

print(f"✅ Training data prepared: {X_train.shape}")

# ========================================
# Step 4: Build LSTM Model
# ========================================
print("\n🏗️ Building LSTM model...")

model = Sequential([
    LSTM(128, return_sequences=True, input_shape=(TIME_STEPS, 1)),
    Dropout(0.2),
    LSTM(64, return_sequences=True),
    Dropout(0.2),
    LSTM(32, return_sequences=False),
    Dropout(0.2),
    Dense(64, activation="relu"),
    Dropout(0.3),
    Dense(1)
])

model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    loss="mae",
    metrics=[keras.metrics.RootMeanSquaredError()]
)

print("\n📋 Model Summary:")
model.summary()

# ========================================
# Step 5: Train the Model
# ========================================
print("\n🚀 Training the model...")
print("   This may take 5-10 minutes...")

history = model.fit(
    X_train, y_train,
    epochs=16,
    batch_size=32,
    validation_split=0.1,
    verbose=1
)

print("✅ Training complete!")

# Plot training history
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].plot(history.history['loss'], label='Training Loss', linewidth=2)
axes[0].plot(history.history['val_loss'], label='Validation Loss', linewidth=2)
axes[0].set_title('Model Loss', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('Loss (MAE)')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

axes[1].plot(history.history['root_mean_squared_error'], label='Training RMSE', linewidth=2)
axes[1].plot(history.history['val_root_mean_squared_error'], label='Validation RMSE', linewidth=2)
axes[1].set_title('Model RMSE', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('RMSE')
axes[1].legend()
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# ========================================
# Step 6: Evaluate on Test Set
# ========================================
print("\n🧪 Evaluating on test set...")
test_data = scaled_data[training_data_len - TIME_STEPS:]
X_test, y_test = [], dataset[training_data_len:]

for i in range(TIME_STEPS, len(test_data)):
    X_test.append(test_data[i-TIME_STEPS:i, 0])

X_test = np.array(X_test)
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))

# Make predictions on test set
test_predictions = model.predict(X_test, verbose=0)
test_predictions = scaler.inverse_transform(test_predictions)

# Calculate metrics
mae = mean_absolute_error(y_test, test_predictions)
rmse = np.sqrt(mean_squared_error(y_test, test_predictions))
r2 = r2_score(y_test, test_predictions)
mape = np.mean(np.abs((y_test - test_predictions) / y_test)) * 100

print(f"\n📊 Model Performance on Test Set:")
print(f"   MAE:   ₹{mae:.2f}")
print(f"   RMSE:  ₹{rmse:.2f}")
print(f"   R²:    {r2:.4f}")
print(f"   MAPE:  {mape:.2f}%")

# ========================================
# Step 7: 3-Day Future Prediction (Iterative)
# ========================================
print(f"\n🔮 Making {FORECAST_DAYS}-day future predictions...")

# Get the last 60 days of actual data
last_60_days = scaled_data[-TIME_STEPS:]
forecast_input = last_60_days.copy()

# Store predictions
future_predictions = []
prediction_dates = []

# Get the last date in dataset
last_date = pd.to_datetime(data['date'].iloc[-1])

# Predict iteratively
for day in range(FORECAST_DAYS):
    # Reshape for prediction
    X_forecast = forecast_input.reshape(1, TIME_STEPS, 1)

    # Predict next day
    predicted_price_scaled = model.predict(X_forecast, verbose=0)

    # Store prediction
    predicted_price = scaler.inverse_transform(predicted_price_scaled)[0][0]
    future_predictions.append(predicted_price)

    # Calculate next date (skip weekends)
    next_date = last_date + timedelta(days=day+1)
    while next_date.weekday() >= 5:  # Skip Saturday(5) and Sunday(6)
        next_date += timedelta(days=1)
    prediction_dates.append(next_date)

    # Update input for next iteration (use prediction as new input)
    forecast_input = np.append(forecast_input[1:], predicted_price_scaled, axis=0)

    print(f"   Day {day+1} ({next_date.strftime('%Y-%m-%d')}): ₹{predicted_price:.2f}")

# ========================================
# Step 8: Visualize Results
# ========================================
print("\n📈 Generating visualizations...")

# Create comprehensive dataframe
train_df = data.iloc[:training_data_len].copy()
test_df = data.iloc[training_data_len:].copy()
test_df['predictions'] = test_predictions

# Create future predictions dataframe
future_df = pd.DataFrame({
    'date': prediction_dates,
    'predictions': future_predictions
})

# Plot 1: Full Historical + Test + Future
fig, ax = plt.subplots(figsize=(16, 8))

train_x = train_df['date'] if 'date' in train_df.columns else train_df.index
test_x = test_df['date'] if 'date' in test_df.columns else test_df.index

ax.plot(train_x, train_df['close'], label="Training Data",
        color='blue', alpha=0.7, linewidth=2)
ax.plot(test_x, test_df['close'], label="Test Data (Actual)",
        color='orange', alpha=0.7, linewidth=2)
ax.plot(test_x, test_df['predictions'], label="Test Predictions",
        color='red', alpha=0.7, linewidth=2, linestyle='--')
ax.plot(future_df['date'], future_df['predictions'],
        label="Future Predictions (3 Days)",
        color='green', alpha=0.9, linewidth=3, marker='o', markersize=8)

ax.set_title(f"{STOCK_SYMBOL} - LSTM Predictions with 3-Day Forecast",
             fontsize=18, fontweight='bold')
ax.set_xlabel("Date", fontsize=14)
ax.set_ylabel("Close Price (₹)", fontsize=14)
ax.legend(fontsize=12)
ax.grid(True, alpha=0.3)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Plot 2: Zoomed - Last 30 days + 3 future days
fig, ax = plt.subplots(figsize=(16, 8))

# Get last 30 days of actual data
last_30_days = data.tail(30).copy()
last_30_x = last_30_days['date'] if 'date' in last_30_days.columns else last_30_days.index

ax.plot(last_30_x, last_30_days['close'],
        label="Recent Actual Prices",
        color='blue', alpha=0.7, linewidth=3, marker='o', markersize=5)
ax.plot(future_df['date'], future_df['predictions'],
        label="3-Day Forecast",
        color='green', alpha=0.9, linewidth=3, marker='s', markersize=10)

# Add annotations for future predictions
for i, (date, price) in enumerate(zip(future_df['date'], future_df['predictions'])):
    ax.annotate(f'₹{price:.2f}',
                xy=(date, price),
                xytext=(10, 10),
                textcoords='offset points',
                fontsize=11,
                fontweight='bold',
                bbox=dict(boxstyle='round,pad=0.5', facecolor='yellow', alpha=0.7),
                arrowprops=dict(arrowstyle='->', connectionstyle='arc3,rad=0'))

ax.set_title(f"{STOCK_SYMBOL} - Last 30 Days + 3-Day Forecast",
             fontsize=18, fontweight='bold')
ax.set_xlabel("Date", fontsize=14)
ax.set_ylabel("Close Price (₹)", fontsize=14)
ax.legend(fontsize=12, loc='best')
ax.grid(True, alpha=0.3)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# ========================================
# Step 9: Save Model and Scaler
# ========================================
print("\n💾 Saving model and scaler...")

# Save model
model_filename = f'lstm_{STOCK_SYMBOL.replace(".", "_").lower()}.keras'
model.save(model_filename)
print(f"   ✅ Model saved: {model_filename}")

# Save scaler (important for deployment!)
scaler_filename = f'scaler_{STOCK_SYMBOL.replace(".", "_").lower()}.pkl'
with open(scaler_filename, 'wb') as f:
    pickle.dump(scaler, f)
print(f"   ✅ Scaler saved: {scaler_filename}")

# ========================================
# Step 10: Summary Report
# ========================================
print("\n" + "="*70)
print("📊 FINAL SUMMARY REPORT")
print("="*70)
print(f"\n🎯 Stock: {STOCK_SYMBOL}")
print(f"📅 Training Period: {TRAIN_START} to {TRAIN_END}")
print(f"📈 Total Training Days: {len(data)}")

print(f"\n🤖 Model Performance:")
print(f"   MAE:  ₹{mae:.2f}")
print(f"   RMSE: ₹{rmse:.2f}")
print(f"   R²:   {r2:.4f}")
print(f"   MAPE: {mape:.2f}%")

print(f"\n🔮 3-Day Future Forecast:")
last_actual_price = data['close'].iloc[-1]
print(f"   Last Actual Price ({data['date'].iloc[-1].strftime('%Y-%m-%d')}): ₹{last_actual_price:.2f}")
print()
for i, (date, price) in enumerate(zip(prediction_dates, future_predictions)):
    change = price - last_actual_price
    change_pct = (change / last_actual_price) * 100
    trend = "📈" if change > 0 else "📉"
    print(f"   {trend} Day {i+1} ({date.strftime('%Y-%m-%d')}): ₹{price:.2f} ({change:+.2f}, {change_pct:+.2f}%)")

print(f"\n💾 Files Saved:")
print(f"   1. {model_filename}")
print(f"   2. {scaler_filename}")

print("\n" + "="*70)
print("✅ Training Complete! Model ready for deployment.")
print("="*70)

# ========================================
# Step 11: Create Deployment Info
# ========================================
deployment_info = {
    'stock_symbol': STOCK_SYMBOL,
    'training_start': TRAIN_START,
    'training_end': TRAIN_END,
    'total_training_days': len(data),
    'time_steps': TIME_STEPS,
    'forecast_days': FORECAST_DAYS,
    'model_file': model_filename,
    'scaler_file': scaler_filename,
    'mae': float(mae),
    'rmse': float(rmse),
    'r2': float(r2),
    'mape': float(mape),
    'last_training_date': str(data['date'].iloc[-1]),
    'last_training_price': float(last_actual_price),
    'future_predictions': [
        {
            'date': date.strftime('%Y-%m-%d'),
            'predicted_price': float(price)
        }
        for date, price in zip(prediction_dates, future_predictions)
    ]
}

# Save deployment info
info_filename = f'deployment_info_{STOCK_SYMBOL.replace(".", "_").lower()}.json'
with open(info_filename, 'w') as f:
    json.dump(deployment_info, f, indent=2)
print(f"\n📄 Deployment info saved: {info_filename}")

print("\n🎉 All done! You can now download the model files for deployment.")