services:
  - type: web
    name: stock-market-api
    env: python
    pythonVersion: "3.11.9"
    buildCommand: |
      pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: FRONTEND_URL
        value: "*"
      - key: RENDER
        value: "true"