services:
  - type: web
    name: stock-market-api
    env: python
    pythonVersion: "3.13.0"
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 2
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: FRONTEND_URL
        value: "*"
      - key: RENDER
        value: "true"